services:
  - type: web
    name: aiblog-api
    env: python
    buildCommand: ""
    startCommand: waitress-serve --host 0.0.0.0 --port 10000 app:app
    envVars:
      - key: PORT
        value: 10000
